// 15 Hamster Reactions Configuration

export const REACTIONS = {
  fist_by_head: {
    id: "fist_by_head",
    name: "LOLLIPOP JOY!",
    gestureName: "FIST",
    gestureSub: "(lollipop)",
    icon: "🍭",
    color: "#ff80bf",
    badgeBg: "#ffe0f0",
    image: "/images/happylollypop.webp",
    verdict: "bro wants a lollipop",
    rawDetector: "fist_by_head",
    description: "Closed fist held right beside your head. Pure unadulterated sugary happiness.",
    instruction: "Hold a closed fist next to your ear/head",
  },
  thumbs_up: {
    id: "thumbs_up",
    name: "HAPPY HAMMY",
    gestureName: "THUMBS UP",
    gestureSub: "(happy)",
    icon: "👍",
    color: "#4ade80",
    badgeBg: "#dcfce7",
    image: "/images/thumb.jpg",
    verdict: "hammy approves of your life choices",
    rawDetector: "thumbs_up",
    description: "Single thumb raised away from your face. Hammy gives you 10/10.",
    instruction: "Give a clean thumbs up into the camera",
  },
  thumbs_down: {
    id: "thumbs_down",
    name: "DISAPPOINTED HAMMY",
    gestureName: "THUMBS DOWN",
    gestureSub: "(sad)",
    icon: "👎",
    color: "#f87171",
    badgeBg: "#fee2e2",
    image: "/images/thumbs down.jpg",
    verdict: "hammy is thoroughly unimpressed",
    rawDetector: "thumbs_down",
    description: "Thumb pointed down. Hammy is heartbroken and sorrowful.",
    instruction: "Point thumb downwards away from face",
  },
  glasses: {
    id: "glasses",
    name: "DISCORD MOD GLASSES",
    gestureName: "PINCH",
    gestureSub: "(glasses)",
    icon: "🤏",
    color: "#60a5fa",
    badgeBg: "#dbeafe",
    image: "/images/discord mod.jpg",
    verdict: "bro is adjusting their bifocals",
    rawDetector: "glasses",
    description: "Pinching thumb and index finger close to face or eyes like putting on glasses.",
    instruction: "Pinch thumb & index finger together near eyes/face",
  },
  finger_mouth: {
    id: "finger_mouth",
    name: "SHH HAMMY",
    gestureName: "FINGER NEAR MOUTH",
    gestureSub: "(shh)",
    icon: "🤫",
    color: "#a78bfa",
    badgeBg: "#ede9fe",
    image: "/images/one finger mouth .jpg",
    verdict: "shhh... hammy is listening to secrets",
    rawDetector: "finger_mouth",
    description: "Index finger held directly in front of lips. Keep it down!",
    instruction: "Hold index finger directly against your lips",
  },
  nerd: {
    id: "nerd",
    name: "NERD HAMSTER",
    gestureName: "FINGER UP",
    gestureSub: "(nerd)",
    icon: "☝️",
    color: "#fb923c",
    badgeBg: "#ffedd5",
    image: "/images/nerd.jpg",
    verdict: "\"erm, actually...\" - 🤓 hammy",
    rawDetector: "nerd",
    description: "Index finger pointed straight up away from mouth. Well actually!",
    instruction: "Point index finger straight up into the air",
  },
  bicep: {
    id: "bicep",
    name: "SWOLE HAMMY",
    gestureName: "BICEP",
    gestureSub: "(strong)",
    icon: "💪",
    color: "#eab308",
    badgeBg: "#fef9c3",
    image: "/images/bicep.jpg",
    verdict: "hammy hit leg day and chest day simultaneously",
    rawDetector: "bicep",
    description: "Elbow bent with wrist raised high above shoulder. Flex those hamster gains!",
    instruction: "Flex arm with elbow out and fist raised high",
  },
  cross_arms: {
    id: "cross_arms",
    name: "NOPE HAMMY",
    gestureName: "CROSS ARMS",
    gestureSub: "(no)",
    icon: "🙅",
    color: "#f43f5e",
    badgeBg: "#ffe4e6",
    image: "/images/cross arms .jpg",
    verdict: "absolutely not. rejected.",
    rawDetector: "cross_arms",
    description: "Both wrists crossed across your chest. Refusal mode activated.",
    instruction: "Cross both forearms/wrists across chest",
  },
  shy: {
    id: "shy",
    name: "SHY HAMMY",
    gestureName: "HANDS ON CHEEKS",
    gestureSub: "(shy)",
    icon: "🥺",
    color: "#f472b6",
    badgeBg: "#fce7f3",
    image: "/images/cinamoroll ham.jpg",
    verdict: "hammy is blushing... please don't look",
    rawDetector: "shy",
    description: "Both hands touching or cupping cheeks. Too cute to handle.",
    instruction: "Cup both hands against your cheeks",
  },
  thinking: {
    id: "thinking",
    name: "PONDERING HAMMY",
    gestureName: "HANDS TOGETHER",
    gestureSub: "(thinking)",
    icon: "🤔",
    color: "#38bdf8",
    badgeBg: "#e0f2fe",
    image: "/images/think .jpg",
    verdict: "calculating the exact trajectory of sunflower seeds",
    rawDetector: "thinking",
    description: "Hands clasped under chin or mouth like a philosopher in deep thought.",
    instruction: "Clasp both hands together under your chin",
  },
  hug: {
    id: "hug",
    name: "HUG HAMMY",
    gestureName: "HANDS AT CHEST",
    gestureSub: "(hug)",
    icon: "🤗",
    color: "#fb7185",
    badgeBg: "#ffe4e6",
    image: "/images/plushie.jpg",
    verdict: "needs a warm squishy embrace right now",
    rawDetector: "hug",
    description: "Hands held together at chest height below chin. Give me a hug!",
    instruction: "Hold both hands together over your chest",
  },
  sad: {
    id: "sad",
    name: "SAD HAMMY",
    gestureName: "HEAD DOWN",
    gestureSub: "(sad)",
    icon: "🙇",
    color: "#94a3b8",
    badgeBg: "#f1f5f9",
    image: "/images/look down side .jpg",
    verdict: "existential hamster dread has arrived",
    rawDetector: "sad",
    description: "Tilt your head downward in sorrow or disappointment.",
    instruction: "Tilt your head downward towards chest",
  },
  two_hands: {
    id: "two_hands",
    name: "TRUCK HAMMY",
    gestureName: "TWO HANDS",
    gestureSub: "(truck)",
    icon: "🚚",
    color: "#ef4444",
    badgeBg: "#fee2e2",
    image: "/images/2 arms out .jpg",
    verdict: "honk honk! beep beep! get out the way!",
    rawDetector: "two_hands",
    description: "Show both open hands up in the frame! Beep beep truck incoming!",
    instruction: "Hold both hands up in the frame",
  },
  side_eye: {
    id: "side_eye",
    name: "SIDE-EYE HAMSTER",
    gestureName: "HEAD TURN",
    gestureSub: "(side-eye)",
    icon: "👀",
    color: "#c084fc",
    badgeBg: "#f3e8ff",
    image: "/images/sideyee.jpg",
    verdict: "criminal offensive bombastic side-eye",
    rawDetector: "side_eye",
    description: "Turn your face to the side while keeping eyes on the camera.",
    instruction: "Turn head noticeably to the left or right",
  },
  default: {
    id: "default",
    name: "POKER-FACE HAMMY",
    gestureName: "NOTHING",
    gestureSub: "(poker face)",
    icon: "😐",
    color: "#a3a3a3",
    badgeBg: "#f5f5f5",
    image: "/images/plain_hamster.png",
    verdict: "hammy is judging you in complete silence",
    rawDetector: "default",
    description: "Plain white meme hamster with no accessories. Blank, deadpan stare.",
    instruction: "Just sit there and stare blankly into the abyss",
  },
};

export const GESTURE_ORDER = [
  "fist_by_head",
  "thumbs_up",
  "thumbs_down",
  "glasses",
  "finger_mouth",
  "nerd",
  "bicep",
  "cross_arms",
  "shy",
  "thinking",
  "hug",
  "sad",
  "two_hands",
  "side_eye",
  "default",
];
